image: docker:latest
services:
  - docker:dind

variables:
  REGISTRY: "${CI_REGISTRY_IMAGE}"
  PUSH: 'true'
  # Change below to match the user and group ID's
  # on the target host machine
  ID: 1000
  GID: 1000
  PLUGDEV: 240
  AUDIO: 18

before_script:
  - apk upgrade -U && apk add bash
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"

autopsy:corretto:
  script:
    - cd autopsy
    - bash ./build corretto

regripper:latest:
  script:
    - cd regripper
    - bash ./build latest

volatility:latest:
  script:
    - cd volatility
    - bash ./build latest

ftkimager:latest:
  script:
    - cd ftkimager
    - bash ./build latest

wireshark:latest:
  script:
    - cd wireshark
    - bash ./build latest
